### ISSUE TITLE
[Feature request] StatusBarWeather message after any linter of SublimeLinter message

### ISSUE THREAD

**Issue by Kristinita** [lowliet/sublimetext-StatusBarWeather#3]
I use some linters of [SublimeLinter](https://github.com/SublimeLinter/SublimeLinter3) framework. If I have error in my code, I see message in Status Bar, example:

![Status Bar](http://i.imgur.com/VIoPbja.png)

StatusBarWeather message now before SublimeLinter message. That's bad, because I can not see last pat of the error of my code, as in the example image.

Could you do that StatusBarWeather message is situated after any linter of SublimeLinter message?

Thanks.

**Comment by ildarkhasanshin** [comment]
new commit
https://github.com/lowliet/sublimetext-StatusBarWeather/commit/dbed37b085b323bce489d4acc5b7e7a13578b724

@Kristinita 
обновил https://github.com/ildarkhasanshin/sublimetext-StatusBarWeather/blob/master/StatusBarWeather.py
![img-2016-09-27-13-15-35](https://cloud.githubusercontent.com/assets/8765305/18865539/9e4d0954-84bd-11e6-9da0-280161d11f5c.png)

**Comment by Kristinita** [comment]
@ildarkhasanshin , спасибо! 

Можно комментарий, что буква `z` означает? Сообщения от StatusBarWeather будут отображаться только после сообщений SublimeLinter или же также после сообщений других плагинов, выводящих информацию в Status Bar?

**Comment by ildarkhasanshin** [comment]
https://www.sublimetext.com/docs/3/api_reference.html
set_status(key, value)
здесь сортировка по параметру key, поэтому добавил вначале z, т.к. це последняя буква

у линтера key = sublimelinter, т.е. первая бухва эс
см. строку 404 /Packages/SublimeLinter/sublimelinter.py
